name: azzorti_captura
description: "Prototipo Modulo M1 V2 (Captura de Precio en Campo) - FR-SIS-09 V5.1"
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
