name:azzorti_captura
description: "Prototipo Modulo M1 V2.3 (OCR mejorado + color por foto) - FR-SIS-09 V5.1"
publish_to: 'none'
version: 2.3.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  path_provider: ^2.1.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_image_labeling: any
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
